---

- name: Add the Docker public GPG key to the apt repo
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80
           id=58118E89F3A912897C070ADBF76221572C52609D
           state=present

- name: Add the Docker repo to the trusted sources list
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install the linux-image-extra package
  apt: name='linux-image-extra-{{ ansible_kernel }}' state=installed

- name: Install Docker
  apt: name=docker-engine state=installed
