---

- name: Install Uncomplicated Firewall
  apt: update_cache={{ update_apt_cache }} state=installed pkg=ufw

- name: Allowed ports for everyone
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "{{ ufw_allowed_ports }}"

- name: Enable ufw/firewall
  ufw: state=enabled policy=deny
